### ISSUE TITLE
Issues with  config.container

### ISSUE THREAD

**Issue by edoardoVD** [tinesoft/ng-scrollreveal#15]
Hi there, 

I'm having issues with ng-scrollreveal, please see attached image of the issue

Using chrome dev tools with the view _**responsive**_ (or just changing the browser window size), if I play around with the dimensions (height of the view/browser) it works, but  **_when I scroll, it does not work._**

![issue](https://user-images.githubusercontent.com/21366085/26942457-5ee52400-4c3f-11e7-8dc7-f96038acfdab.gif)

My dependencies and code:

@angular: ^4.0.0
 "ng-scrollreveal": "^2.0.2",

**app.component.ts**

```
@NgModule({
  declarations: [
   
  ],
  imports: [ 
    NgsRevealModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

**app.component.html**

```
<!--<layout></layout>-->
 
<style>
    .item {
        width: 50px;
        height: 50px;
        background-color: red;
        padding: 10px;
        margin: 10px;
    }
</style>



<div class="item" [ngsReveal]="{ reset: true}" >..</div>

<div class="item" [ngsReveal]="{ reset: true}" >..</div>

<div class="item" [ngsReveal]="{ reset: true}" >..</div>

<div class="item" [ngsReveal]="{ reset: true}" >..</div>

<div class="item" [ngsReveal]="{ reset: true}" >..</div>

<div class="item" [ngsReveal]="{ reset: true}" >..</div>


<div class="itemset" [ngsRevealSet]="{reset:true}" [ngsSelector]="'.item'">
    <div class="item item1">Item 1</div>
    <div class="item item2">Item 2</div>
    <div class="item item3">Item 3</div>
    <div class="item item4">Item 4</div>
    <div class="item5">Item 5 (will not be animated)</div>
</div>

```

THANKS !

**Comment by edoardoVD** [comment]
OK so I changed the title of the issue, it does animate and if angular 4 would be the issues, it would break or not animate or something else.. . .. I think my problem lies with setting the correct container settings.. . .

Some code on the **AppComponent** 
```

export class AppComponent implements AfterViewInit {
  constructor(private config: NgsRevealConfig) {
    // customize default values of ng-scrollreveal directives used by this component tree
    //config.duration = 5000;

    config.easing = 'cubic-bezier(0.645, 0.045, 0.355, 1)';

    //config.container = document.querySelector('.xxx') 

    console.log('config.container', this.config.container);
    console.log("document.querySelector('.html')", document.querySelector('html'));
    console.log('window.document.documentElement', window.document.documentElement);
    this.config.container = window.document.documentElement;

  }
```

duration and easing do work but, while trying to set the container ... 

According to the config d.ts, container is of type HTMLElement
 
```
export declare class NgsRevealConfig {

    container?: HTMLElement;
```

According to the scrollreveal documentation on the default config settings (https://github.com/jlmakes/scrollreveal#2-configuration)

 
Doing this on the constructor of AppComponent
 

```
this.config.container = document.querySelector('xxx');
this.config.container = '.xxx'
 
```

**Give mes a type error since Element is not assignable to container?: HTMLElement;**

**Comment by tinesoft** [comment]
Hi @edoardoVD 

Good catch about the type of container...
Even more complicated enough, it seems that the actual type returned by `document.querySelector(selector)` depends on the passed selector:

See here, a extract of **lib.dom.d.ts** file

![image](https://user-images.githubusercontent.com/4053092/26951028-04b4b48a-4ca0-11e7-8623-54a9454c033f.png)


Anyway, I will relax the type of `container` into :` container?: Element|string`  ,as it seems possible to set it to the selector as string as well.

**Comment by edoardoVD** [comment]
thanks for looking intos this, 

any idea how can I get it to work ?

Still no luck with my project : (

**Comment by tinesoft** [comment]
Just published [v2.0.3](https://www.npmjs.com/package/ng-scrollreveal), 

Could you update your deps, then` yarn upgrade` (or `rm -rf node_modules/ && npm install`)?

Feel free to re-open if still having issues, and it look at it in more details.

Cheers,

**Comment by edoardoVD** [comment]
@tinesoft , thanks for the super fast update on the package

So here's the current status:

Updated ngscrollreveal to 2.0.3
I'm not tempering in anyway with the configuration settings of scrollreveal

**Still not working**

Things to know:
I'm using a router outlet
this is how my page structure is


![test](https://user-images.githubusercontent.com/21366085/26952853-773bd3bc-4c64-11e7-9c59-831f35f1af0b.png)

html
-- body
---  ng-component
----   div #testClass
-----    div item
 -----   div item
 -----   div item

my home.component.html has:

<div class="item" [ngsReveal]="{ reset: true}" >..</div>
<div class="item" [ngsReveal]="{ reset: true}" >..</div>
<div class="item" [ngsReveal]="{ reset: true}" >..</div>
<div class="item" [ngsReveal]="{ reset: true}" >..</div>
<div class="item" [ngsReveal]="{ reset: true}" >..</div>
<div class="item" [ngsReveal]="{ reset: true}" >..</div>

**Comment by tinesoft** [comment]
Hi @edoardoVD ,

I haven't looked closely enough yesterday (was getting late :) )
But the problem here, is that you have the  `[ngsReveal]` on each single item you want to animate 
```
div class="item" [ngsReveal]="{ reset: true}" >..
div class="item" [ngsReveal]="{ reset: true}" >..
div class="item" [ngsReveal]="{ reset: true}" >..
div class="item" [ngsReveal]="{ reset: true}" >..
div class="item" [ngsReveal]="{ reset: true}" >..
div class="item" [ngsReveal]="{ reset: true}" >..
```
AND that those items **_are already in the viewport (i.e visible)_**, so nothing happens, unless you resize the viewport.

If your intent was to animate those items sequentially, you can wrap them in a parent div and add:  `[ngsRevealSet]="{reset:true, duration=5000}" [ngsSelector]="'.item'"`, like you do in the rest of your `app.component.html`

**Comment by edoardoVD** [comment]
😠 ok found the issue. . . . . . 
lesson learn.. . . look everywere. . . . 👀 

so the problem was ...... . . . on one of my core css files I have

body {
    height: 100%;
    width: 100%;
    margin: 0;
    **//overflow-x: hidden;**
}

this ------------------> overflow-x: hidden; **MESSESS UP scrollreveal**
on the bright side, an update was made to the project _(container?: Element|string)_
