### ISSUE TITLE
Update for Angular 4

### ISSUE THREAD

**Issue by hgoebl** [tinesoft/ng-scrollreveal#32]
Could you please upgrade package.json to also accept Angular 4.x?
Maybe something similar to

```
"peerDependencies": {
   "@angular/common": "^2.3.1 || >=4.0.0",
   "@angular/compiler": "^2.3.1 || >=4.0.0",
   "@angular/core": "^2.3.1 || >=4.0.0",
 },
```

**Comment by tinesoft** [comment]
Hi @hgoebl 

You should be able to use current version of the library with a project targetting Angular v4 (see integrated [demo](https://github.com/tinesoft/ng-scrollreveal/tree/master/demo) app for example).
In fact, current `peerDependencies` being on  **^**`2.0.0` , means that every version of Angular >=2.0.0 is eligible:

```
"peerDependencies": {
   "@angular/common": "^2.0.0",
   "@angular/core": "^2.0.0"
 },
```

What issues are you experiencing?

**Comment by hgoebl** [comment]
If I remember correctly, then the problem only occurred with npm 2.x. After upgrading to npm 3.10 `npm install` only showed warnings.
