### ISSUE TITLE
Problem with Angular Universal (Server Side Rendering)

### ISSUE THREAD

**Issue by Zaramao** [tinesoft/ng-scrollreveal#50]
Hello! I have a problem with ng-scrollreveal in Angular 4. It actually works fine in local dev environment, but on `ng build --prod` once it builds the app and once it's on a live server, it returns errors `ERROR ReferenceError: ScrollReveal is not defined` and `ERROR Error: Uncaught (in promise): ReferenceError: ScrollReveal is not defined
ReferenceError: ScrollReveal is not defined` and it's not working.

I have included `NgsRevealModule` in my `app.module.ts`, and as I said, it works all fine with `ng serve` command. I am quite new in Angular, so I might be missing something? Thanks in advance and thank you for this amazing module

#Edit 
Also I've been using angular-ssr for server side rendering, and once build is done I usually run a command so it renders out routes as pages, since it's a small app and only has 4-5 pages I didn't set it to be on-demand rendering, but rather this simple solution. But as I run the command, the terminal also returns an error `Unhandled Promise rejection: ScrollReveal is not defined ; Zone: <root> ; Task: Promise.then ; Value: { ReferenceError: ScrollReveal is not defined`

**Comment by tinesoft** [comment]
Hi @Zaramao 

Thanks for using the lib and for your issue.

I haven't tested the module in a SSR (Server Side Rendering) context, but from the error message you get, i can conclude that it does not found the needed `ScrollReveal` object exposed in the global `window` object  from the node server. 

Are you sure the original `scrollreveal.js` is added to your final bundle used by the SSR? like it is done for the client app?

**Comment by Zaramao** [comment]
@tinesoft Thank you for your response, I will look into it! :)

**Comment by tinesoft** [comment]
I'm a bit busy at the moment, but i'll try to have a closer look also,
 maybe on the weekend

**Comment by tinesoft** [comment]
Hi @Zaramao 

Just released [ng-scrollreveal@2.1.0](https://github.com/tinesoft/ng-scrollreveal/releases/tag/v2.1.0) that add angular universal support.

Cheers!

**Comment by Zaramao** [comment]
@tinesoft Thanks a lot! Will test it out asap and let you know the results :)
