### ISSUE TITLE
 Unable to inject ngs-reveal-config service in root component

### ISSUE THREAD

**Issue by huckpilot** [tinesoft/ng-scrollreveal#6]
Hey @tinesoft
I am having an issue injecting the config service in my root component so that I may provide default values for all the nsReveal directives in my app.

In my app.component.ts: 
```
import { NgsRevealConfig } from 'ng-scrollreveal';
```

Similarly attempting to add it to my app.module.ts: 
```
import { NgsRevealModule, NgsRevealConfig } from 'ng-scrollreveal';
```

I'm not sure what I am doing wrong, I'd really appreciate your help!

**Comment by tinesoft** [comment]
Hi @huckpilot 

I released v2.0.1, which should allow you global configuration of `ng-scrollreveal`.
I also updated the docs explaining how to proceed, please have a look at here: https://github.com/tinesoft/ng-scrollreveal#global-configuration

Feel free to re-open, if you still have an issue.

Cheers
