### ISSUE TITLE
Angular 4.4.5+

### ISSUE THREAD

**Issue by mikebrsv** [tinesoft/ng-scrollreveal#67]
OS and Version: Windows 10
ng --version: 1.4.3

Get
+-- UNMET PEER DEPENDENCY @angular/common@4.4.6
+-- UNMET PEER DEPENDENCY @angular/core@4.4.6
on $ npm install --save ng-scrollreveal. Same on 4.4.5. Is this library not compatible with newer versions of Angular 4?

**Comment by tinesoft** [comment]
Hi,
Can you post your `package.json` file, along with the npm install log?
This library is normally compatible with any version of Angular, staring at `v2.0.0`

**Comment by tinesoft** [comment]
hi @TechBright ,

Please open a new issue with repro steps, as this one has nothing to do with SSR.
For your information, the library supports SSR since v2.1.0 (https://github.com/tinesoft/ng-scrollreveal/pull/52)

**Comment by lisandropat** [comment]
I'm getting the **_Uncaught (in promise): ReferenceError: ScrollReveal is not defined_** even though I followed the instructions.

`{
  "name": "wumbox-landing",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.0.1",
    "@angular/cdk": "^8.0.1",
    "@angular/common": "~8.0.1",
    "@angular/compiler": "~8.0.1",
    "@angular/core": "~8.0.1",
    "@angular/flex-layout": "^8.0.0-beta.26",
    "@angular/forms": "~8.0.1",
    "@angular/material": "^8.0.1",
    "@angular/platform-browser": "~8.0.1",
    "@angular/platform-browser-dynamic": "~8.0.1",
    "@angular/router": "~8.0.1",
    "ngx-scrollreveal": "^3.0.0",
    "ngx-swiper-wrapper": "^8.0.0",
    "rxjs": "~6.4.0",
    "scrollreveal": "^4.0.5",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular/cli": "~8.0.3",
    "@angular/compiler-cli": "~8.0.1",
    "@angular/language-service": "~8.0.1",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }
}
`
