### ISSUE TITLE
Installation instructions for Angular 6

### ISSUE THREAD

**Issue by botoxparty** [tinesoft/ng-scrollreveal#72]
Hey,

Love this directive thanks for publishing it! Just wanted to bring it up-to-date with Angular today.

Was just trying to get it going with a fresh Angular 6 project. I found a lot of the steps in the installation instructions can be skipped:

**All you need to do to get it working is...**

`npm install --save ng-scrollreveal`

Then import to the main module

```
import {NgsRevealModule} from 'ng-scrollreveal';
 
@NgModule({
  declarations: [AppComponent, ...],
  imports: [NgsRevealModule.forRoot(), ...],  
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

and finally in **index.html** before the closing </body> tag.

`<script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>`

- - - - - - -

Hopefully this helps someone, also let me know if you see any problems with my method.

Cheers

### OS and Version?
OS X High Sierra

### Versions
Angular CLI: 6.0.8
Node: 10.5.0
OS: darwin x64
Angular: 6.0.6

### Desired functionality
Up-to-date installation instructions.

**Comment by JonasJW** [comment]
It doesn't work for me I get these errors:

`ERROR in node_modules/ng-scrollreveal/services/ngs-reveal.service.d.ts(1,23): error TS2688: Cannot find type definition file for 'scrollreveal'.
node_modules/ng-scrollreveal/services/ngs-reveal.service.d.ts(9,19): error TS2503: Cannot find namespace 'scrollReveal'.
node_modules/ng-scrollreveal/services/ngs-reveal.service.d.ts(27,63): error TS2503: Cannot find namespace 'scrollReveal'.
node_modules/ng-scrollreveal/services/ngs-reveal.service.d.ts(35,109): error TS2503: Cannot find namespace 'scrollReveal'.`

I tried so much to get ScrollReveal to work but it just wont work

**Comment by botoxparty** [comment]
have you declared it in your scripts in your JSON file?

```
      "scripts": [
        "../node_modules/scrollreveal/dist/scrollreveal.js"
      ],


```

looks like it might not be. if you post your project somewhere I can debug it for you.

**Comment by JonasJW** [comment]
Thanks for the Reply!I do have it declared in my scripts Array. I tried .min.js and .js but both give me this arrow. However somehow it works no, I can set ngsReveal to an Element and it is animated but the error still shows up in my console...

**Comment by botoxparty** [comment]
Did you install the typings for ScrollReveal JS?

`npm install --save-dev @types/scrollreveal`

**Comment by JonasJW** [comment]
That seems to be the solution. Thank you so much for helping!

**Comment by tinesoft** [comment]
@JonasJW : I was literally writing a response just now... you beat me by 1sec!

Thanks @botoxparty  for your answers! i'd have given the same ;)

Closing now
