### ISSUE TITLE
support scrollreveal 4.0.0

### ISSUE THREAD

**Issue by sfabriece** [tinesoft/ng-scrollreveal#73]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```
https://github.com/scrollreveal/scrollreveal/blob/master/CHANGELOG.md

**Comment by tinesoft** [comment]
Hi @sfabriece ,  

I've got you covered! Support for `ScrollReveal v4.x.x` is almost done and should drop this week or the next 😃 
Stay tuned

**Comment by tinesoft** [comment]
Close by https://github.com/tinesoft/ng-scrollreveal/pull/75

**Comment by sfabriece** [comment]
awesome @tinesoft 😄
