### ISSUE TITLE
how can you show them when they are on a scroll position

### ISSUE THREAD

**Issue by allaerd** [tinesoft/ng-scrollreveal#8]
Hi,

I want to show slide 2,3,4 when i scroll to them. Now they are animated all at once. 
What do i need to change to have this behavior?

html:
```
<div class="itemset about" [ngsRevealSet]="{reset: true, container: '.itemset'}" [ngsSelector]="'.item'">
  <div class="slide item one"> Block One </div>
  <div class="slide item two"> Block Two </div>
  <div class="slide item three"> Block Three </div>
  <div class="slide item four"> Block Four </div>
</div>
```
css:
```
.slide {
  position: relative;
  height:400px;
}
```

Kind regards,

Allaerd

**Comment by tinesoft** [comment]
Hi @allaerd ,

Remove the ` container:  '.itemset'` from the `[ngsRevealSet]` options, and you should be good!

See this working [plunker](https://plnkr.co/edit/fzzpQVgvXcfOXj0N4Ogp?p=preview).

Also, you can play with `[ngsInterval]` option to adjust the delay (in mlillis) between each item's animation.


Cheers,

**Comment by tinesoft** [comment]
No feedback in 10 days, closing issue.

**Comment by allaerd** [comment]
Hi,

sorry yes. IT works great. Thanks for the feedback

regards,

Allaerd
