### ISSUE TITLE
is it possible to upgrade this library to angular 4 ?

### ISSUE THREAD

**Issue by rainstormza** [tinesoft/ng-scrollreveal#9]
I'm using angular-cli 1.0.0 and angular 4 now.
I 've tried to use this lib to my angular 4 project and it works fine.
anyway , Does it better to upgrade this lib to angular 4 too ?

thanks :) @tinesoft

**Comment by tinesoft** [comment]
Hi @rainstormza ,

The library works fine with all versions of angular starting from 2.0.0.
As i don't use any specific feature of angular v4+, there is no need to require 
dependencies to be v4+ (needlessly too much restrictive).

Besides, the library declares `peerDependencies` (not strict `dependencies`), so you can use whatever version of angular you like in your project.

```  
"peerDependencies": {
    "@angular/common": "^2.0.0",
    "@angular/core": "^2.0.0",
    "scrollreveal": "^3.2.0"
  }
```


Cheers
