### ISSUE TITLE
Error in jest test

### ISSUE THREAD

**Issue by Senshi111** [tinesoft/ng-scrollreveal#98]
### When i run test with Jest i get this error. 
```
import { RouterTestingModule } from '@angular/router/testing';
import { AppComponent } from './app.component';
.....
import { NgsRevealModule } from 'ngx-scrollreveal';

describe('AppComponent', () => {
  beforeEach(async(() => {

    TestBed.configureTestingModule({
      imports: [
        RouterTestingModule,
       ....
        NgsRevealModule

      ],

      declarations: [
        AppComponent,
        ...
        ...

      ]
    }).compileComponents();
  }));

  it('should create the app', () => {
    const fixture = TestBed.createComponent(AppComponent); => ReferenceError: ScrollReveal is not defined Jest
    const app = fixture.componentInstance;
    expect(app).toBeTruthy();
  });
```
 is there a way to fix it?
Thanks

**Comment by tinesoft** [comment]
Hi,

Without seeing your configuration files, it is hard to be more helpful...
but this error generally means that `Scrollreveal JS` library cannot be found by  the test environment (as a reminder,`ngx-scrollreveal` depends on that library to do its job).

So, make sure that you reference the `scrollreveal.js` file in test config. 
If your are using the CLI, make sure that `scrollreveal` is listed as a [global script](https://github.com/angular/angular-cli/wiki/stories-global-scripts) in your `angular.json`:

```
"scripts": [
              "node_modules/scrollreveal/dist/scrollreveal.js"
            ]
```

**Comment by Senshi111** [comment]
Sorry i forgot to include my angular.json
Here it is

```angular.json```

```
"scripts": [
              "./node_modules/scrollreveal/dist/scrollreveal.js"
            ]

```

Everything works fine until i run test. Then i got that error

**Comment by tinesoft** [comment]
Can you post Jest related config files as well?

**Comment by Senshi111** [comment]
sure 
```
package.json
```
```
{
  "name": ....",
  "version": "1.0.0",
  "scripts": {
    ....
    "test": "jest",
    "lint": "ng lint",
    "e2e": "cypress open",
   ....
  },
  "private": true,
  "dependencies": {
   ....
  },
  "devDependencies": {
   ....
"@types/scrollreveal": "^0.0.5",
  },
  "jest": {
    "preset": "jest-preset-angular",
    "setupFilesAfterEnv": [
      "<rootDir>/src/setupJest.ts"
    ],
    "testPathIgnorePatterns": [
      "<rootDir>/node_modules/",
      "<rootDir>/dist/",
      "<rootDir>/src/test.ts",
      "<rootDir>/cypress/",
      "<rootDir>/src/environments/"
    ],
    "globals": {
      "ts-jest": {
        "tsConfig": "<rootDir>/tsconfig.spec.json",
        "stringifyContentPathRegex": "\\.html$",
        "astTransformers": [
          "<rootDir>/node_modules/jest-preset-angular/build/InlineFilesTransformer"
        ]
      }
    }
  }
}

```
```
tsconfig.spec.json
```

```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "outDir": "./out-tsc/spec",
    "types": [
      "jest",
      "node"
    ]
  },
  "files": [
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.spec.ts",
    "src/**/*.d.ts"
  ]
}

```
and i have that setupJest.ts so i can import jest-preset-angular


i just use in my html [ngsReveal]="{ reset: true}" nothing else

**Comment by tinesoft** [comment]
As described in the [jest-preset-angular](https://github.com/thymikee/jest-preset-angular#allow-vendor-libraries-like-jquery-etc) page, you should import the `ScrollrevealJS` in your `setupJest.ts` file , like so: 

```
import ScrollReveal from 'scrollreveal';
global.ScrollReveal = ScrollReveal;
````

**Comment by Senshi111** [comment]
yeah that works.  I was trying to declare it in other place.

Thanks

you have to import like this
import { global } from '@angular/compiler/src/util';
import ScrollReveal from 'scrollreveal';
global.ScrollReveal = ScrollReveal;
